server:
  port: 9081
spring:
  datasource:
    # mysql ???
    url: jdbc:mysql://10.70.12.67:3308/kg_db?characterEncoding=utf-8&useSSL=false
    # mysql ???
    username: root
    # mysql ??
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
